export const filterTemplate = {
    "Include Year Toggle": "Include Year",
    "Claim Dates Included": "2020/01/01 to 2021/01/01",
    "Code Set 1 - A - Code Values": "",
    "Code Set 1 - A - Code Type": "^%",
    "Code Set 1 - B - Code Type": "^%",
    "Code Set 1 - B - Code Values": "",
    "Code Set 1 - C - Code Type": "^%",
    "Code Set 1 - C - Code Values": "",
    "Code Set 1 - D - Code Values": "",
    "Code Set 1 - D - Code Type": "^%",
    "Code Set 2 - Inclusion vs Exclusion": "Include",
    "Code Set 2 - A - Code Type": "^%",
    "Code Set 2 - B - Code Type": "^%",
    "Code Set 2 - A - Code Values": "",
    "Code Set 2 - B - Code Values": "",
    "Code Set 2 - C - Code Type": "^%",
    "Code Set 2 - D - Code Type": "^%",
    "Code Set 2 - C - Code Values": "",
    "Code Set 2 - D - Code Values": "",
    "Code Set 3 - Inclusion vs Exclusion": "Include",
    "Code Set 3 - A - Code Type": "^%",
    "Code Set 3 - A - Code Values": "",
    "Code Set 3 - B - Code Type": "^%",
    "Code Set 3 - B - Code Values": "",
    "Code Set 3 - C - Code Type": "^%",
    "Code Set 3 - C - Code Values": "",
    "Code Set 3 - D - Code Type": "^%",
    "Code Set 3 - D - Code Values": "",
    "Coverage Types Selector": "none",
    "Include Gender Breakout Toggle": "Do Not Include Gender",
    "Include Age Breakout Toggle": "Do Not Include Age",
    "Include State Breakout Toggle": "Do Not Include State",
    "Gender Filter": "",
    "Age Filter": "[17,64]",
    "Year Filter": "",
    "State Filter": "",
    "Include Ethnicity Breakdown": "Do Not Include Ethnicity",
    "Ethnicity Filter": ""
};

export const setFilterMapping = [
    { mapping: [{ selectedKey: 'Code Set 1 - A - Code Type', values: 'Code Set 1 - A - Code Values' }, { selectedKey: 'Code Set 1 - B - Code Type', values: 'Code Set 1 - B - Code Values' }, { selectedKey: 'Code Set 1 - C - Code Type', values: 'Code Set 1 - C - Code Values' }, { selectedKey: 'Code Set 1 - D - Code Type', values: 'Code Set 1 - D - Code Values' }], combinator: '' },
    { mapping: [{ selectedKey: 'Code Set 2 - A - Code Type', values: 'Code Set 2 - A - Code Values' }, { selectedKey: 'Code Set 2 - B - Code Type', values: 'Code Set 2 - B - Code Values' }, { selectedKey: 'Code Set 2 - C - Code Type', values: 'Code Set 2 - C - Code Values' }, { selectedKey: 'Code Set 2 - D - Code Type', values: 'Code Set 2 - D - Code Values' }], combinator: 'Code Set 2 - Inclusion vs Exclusion' },
    { mapping: [{ selectedKey: 'Code Set 3 - A - Code Type', values: 'Code Set 3 - A - Code Values' }, { selectedKey: 'Code Set 3 - B - Code Type', values: 'Code Set 3 - B - Code Values' }, { selectedKey: 'Code Set 3 - C - Code Type', values: 'Code Set 3 - C - Code Values' }, { selectedKey: 'Code Set 3 - D - Code Type', values: 'Code Set 3 - D - Code Values' }], combinator: 'Code Set 3 - Inclusion vs Exclusion' },
];

export const feasibilityToFilterMapping = {
    dateRange: 'Claim Dates Included',
    coverageType: 'Coverage Types Selector',
    ageRange: 'Age Filter',
    ethnicity: 'Ethnicity Filter',
    gender: 'Gender Filter',
    zipCodes: null,
    sets: setFilterMapping,
    showDemographics: null,
};